### ISSUE TITLE
Flying not enabled on the server 

### ISSUE THREAD

**Issue by Kaseem00** [gamingnetwork123/e6e#1]
Hi I have just used a slow falling charm  and  just kicked for that reason as the title says even when I try to rejoin the server 
![image](https://user-images.githubusercontent.com/102190657/159584341-3d95cf85-3817-49ba-9fab-3b72785909c7.png)
Once the slow falling finished that's when I got Kicked

**Comment by zxoltari** [comment]
was aware

**Comment by zxoltari** [comment]
fixed on new config change
